### ISSUE TITLE
Randomly cannot unpack error from trigger_manual_sync_connection

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [PrefectHQ/prefect-airbyte#17]
Hi,

I'm reporting a weird behavior I'm facing while trying to trigger prefect-airbyte task. Most of the time it works well but sometimes I got this error : 
```
job_id, job_created_at = airbyte.trigger_manual_sync_connection(
TypeError: cannot unpack non-iterable NoneType object
``` 

It would mean that this function returns a None object but not specific errors which makes the debugging pretty tricky.

On the airbyte side, the prefect task has created 2 jobs: one failing and one successful.

Full log https://pastebin.com/4xZBJAYd

**Comment by desertaxle** [comment]
Based on the code in `trigger_manual_sync_connection`, I suspect that the Airbyte server is returning a status code other than 200 or 404. We'll need to add some additional status code handling.
